### ISSUE TITLE
Poor pom.xml configuration feedback

### ISSUE THREAD

**Issue by 0mega** [Byclosure/bundler-maven-plugin#2]
While using this plugin in our project we had a variable missing (working-dir) which made the bundle:install fail and there was no useful feedback from the plugin.

What do you think about logging an informative message when there is a variable missing?

**Comment by Byclosure** [comment]
If the build fails without that configuration, then it should be annotated as **required** and maven would fail with a message stating that the configuration is missing.

https://github.com/Byclosure/bundler-maven-plugin/blob/master/src/main/java/com/byclosure/maven/plugins/middleman/AbstractJRubyMojo.java#L20-L24

**Comment by yarcub** [comment]
If the build fails without that configuration, then it should be annotated as **required** and maven would fail with a message stating that the configuration is missing.

If not required, the default value should be a valid one.

https://github.com/Byclosure/bundler-maven-plugin/blob/master/src/main/java/com/byclosure/maven/plugins/middleman/AbstractJRubyMojo.java#L20-L24
